bit more simplification

diff --git a/functions/cleanup b/functions/cleanup
--- a/functions/cleanup
+++ b/functions/cleanup
@@ -3,24 +3,36 @@
 # Update the list of packages in 'data/purge.list' to suit your preferences
 # Listed packages that are are not any system-crucial software to avoid breakage
 
-dir="$(dirname "$0")"
-
+# Remove unused preinstalled apps
 function purge_unused {
-	echo_message title "Starting 'purge_unused' function"
+	echo_message title "Starting 'purge_unused' function..."
 	# Check list
 	LIST=$(dirname "$0")'/data/purge.list'
 	# Draw window
 	if (eval `resize` && whiptail \
-		--title "Remove Pre-installed Applications" \
+		--title "Remove Un-used Pre-installed Applications" \
 		--yesno "Current list of pre-installed apps to remove: \n\n$(cat $LIST) \n\nAre you sure you want proceed?" \
 		$LINES $COLUMNS $(( $LINES - 12 )) \
 		--scrolltext ) then
-		echo_message info 'Removing pre-installed apps...'
-		# Admin privileges
-		elevate_privilege "dnf remove -y $(cat $LIST)"
+		echo_message header 'Removing unused pre-installed apps...'
+		# Remove loop
+		for PACKAGE in $(cat $LIST); do
+			# Check if package is installed
+			if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
+				# Show already removed message
+				echo_message info "Package '$PACKAGE' already removed."
+			else
+				# Remove package
+				echo_message info "'$PACKAGE' is installed. Removing..."
+				# Admin privileges
+				elevate_privilege "dnf remove -y $PACKAGE"
+				# Done
+				echo_message success "'$PACKAGE' removal is complete."
+			fi
+		done
 		# Done
-		echo_message success 'Done.'
-		whiptail --title "Finished" --msgbox "Removal of pre-installed packages complete." 8 78
+		echo_message success 'Removal of unused packages complete.'
+		whiptail --title "Finished" --msgbox "Unwanted pre-installed apps have been removed." 8 64
 		cleanup
 	else
 		cleanup
@@ -30,7 +42,7 @@ function purge_unused {
 # Remove Orphaned Packages
 function remove_orphans {
 	echo_message title "Starting 'remove_orphans' function"
-	echo_message info 'Removing orphaned packages...'
+	echo_message header 'Removing orphaned packages...'
 	# Admin privileges
 	elevate_privilege "dnf autoremove -y"
 	# Done
@@ -42,7 +54,7 @@ function remove_orphans {
 # Remove Duplicate Packages
 function remove_duplicates {
 	echo_message title "Starting 'remove_duplicates' function"
-	echo_message info 'Removing duplicate packages...'
+	echo_message header 'Removing duplicate packages...'
 	# Admin privileges
 	elevate_privilege "dnf remove $(dnf repoquery --duplicated --latest-limit -1 -q)"
 	# Done
@@ -54,7 +66,7 @@ function remove_duplicates {
 # Clean Cache
 function clean_cache {
 	echo_message title "Starting 'clean_cache' function"
-	echo_message info 'Cleaning package cache...'
+	echo_message header 'Cleaning package cache...'
 	# Admin privileges
 	elevate_privilege "dnf clean packages"
 	# Done
@@ -65,8 +77,12 @@ function clean_cache {
 
 # Cleanup System
 function cleanup {
-	eval `resize` 
-	CLEANUP=$(whiptail \
+	echo_message title "Starting 'cleanup' function"
+	# check exit status
+	EXITSTATUS=$?
+	if [ $EXITSTATUS = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "System Cleanup" \
 		--menu "\nWhat would you like to do?" \
@@ -77,10 +93,6 @@ function cleanup {
 		remove_duplicates	'Remove duplicate packages' \
 		purge_unused		'Remove unused pre-installed packages' \
 		3>&1 1>&2 2>&3)
-
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$CLEANUP
 	else
 		main
 	fi
diff --git a/functions/codecs b/functions/codecs
--- a/functions/codecs
+++ b/functions/codecs
@@ -7,10 +7,7 @@ function openh264_codec {
 	NAME="OpenH264 Codec"
 	PACKAGE=gstreamer1-plugin-openh264
 	# Check if package is installed
-	check_packages $PACKAGE
-	EXITSTATUS=$?
-	# If package is not installed
-	if [ $EXITSTATUS = 1 ]; then
+	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
 		echo_message info "$NAME is not installed. Proceeding"
 		# Add repository
 		echo_message info "Enabling $NAME repository..."
@@ -19,9 +16,8 @@ function openh264_codec {
 		echo_message info "Installing $NAME..."
 		elevate_privilege "dnf install -y $PACKAGE"
 		# Done
-		echo_message success 'Done.'
+		echo_message success "Installation of '$PACKAGE' complete."
 		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
-		status=1
 		install_codecs
 	else
 		# Already installed
@@ -75,9 +71,11 @@ function gstreamer_nonfree {
 # Install Codecs
 function install_codecs {
 	echo_message title "Starting 'install_codecs' function"
-	# Variables
-	eval `resize`
-	CODECS=$(whiptail \
+	# check exit status
+	EXITSTATUS=$?
+	if [ $EXITSTATUS = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "Multimedia Codecs" \
 		--menu "\nWhich multimedia codecs would you like to install?" \
@@ -89,10 +87,6 @@ function install_codecs {
 		'ffpmeg_codecs'		'FFmpeg Codecs' \
 		'openh264_codec'	'OpenH264 Codec' \
 		3>&1 1>&2 2>&3)
-
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$CODECS
 	else
 		main
 	fi
diff --git a/functions/repos b/functions/repos
--- a/functions/repos
+++ b/functions/repos
@@ -47,48 +47,44 @@ function add_flatpak_repo() {
 # Add Repositories
 function repositories {
 	echo_message title "Starting 'repositories' function"
-	eval `resize` 
-	EXITSTATUS=$?
-	if [ $EXITSTATUS = 0 ]; then
-		status="0"
-		while [ "$status" -eq 0 ]; do
-			REPOS=$(whiptail \
-				--notags \
-				--title "Third-Party Repositories" \
-				--menu "\nWhat third-party repositories would you like to add?" \
-				--ok-button "Install" \
-				--cancel-button "Go Back" \
-				$LINES $COLUMNS $(( $LINES - 12 )) \
-				"rpmfusion_free"		"RPM Fusion (Free)" \
-				"rpmfusion_nonfree"		"RPM Fusion (Non-free)" \
-				"flathub"				"FlatHub" \
-				3>&1 1>&2 2>&3)
+	# check exit status
+	EXITSTATUS="0"
+	while [ "$EXITSTATUS" -eq 0 ]; do
+		# Draw window
+		REPOS=$(eval `resize` && whiptail \
+			--notags \
+			--title "Third-Party Repositories" \
+			--menu "\nWhat third-party repositories would you like to add?" \
+			--ok-button "Install" \
+			--cancel-button "Go Back" \
+			$LINES $COLUMNS $(( $LINES - 12 )) \
+			"rpmfusion_free"		"RPM Fusion (Free)" \
+			"rpmfusion_nonfree"		"RPM Fusion (Non-free)" \
+			"flathub"				"FlatHub" \
+			3>&1 1>&2 2>&3)
 
-			case "${REPOS}" in
-			# RPM Fusion Free
-			rpmfusion_free)
-				add_rpmfusion free
-				repositories
-			;;
-			# RPM Fusion Non-free
-			rpmfusion_nonfree)
-				add_rpmfusion nonfree
-				repositories
-			;;
-			# FlatHub
-			flathub)
-				REPONAME="flathub"
-				REPO="https://dl.flathub.org/repo/flathub.flatpakrepo"
-				add_flatpak_repo $REPONAME $REPO
-				repositories
-			;;
-			# Go Back
-			*) status=1
-				main
-			;;
-			esac
-		done
-	else
-		main
-	fi
+		case "${REPOS}" in
+		# RPM Fusion Free
+		rpmfusion_free)
+			add_rpmfusion free
+			repositories
+		;;
+		# RPM Fusion Non-free
+		rpmfusion_nonfree)
+			add_rpmfusion nonfree
+			repositories
+		;;
+		# FlatHub
+		flathub)
+			REPONAME="flathub"
+			REPO="https://dl.flathub.org/repo/flathub.flatpakrepo"
+			add_flatpak_repo $REPONAME $REPO
+			repositories
+		;;
+		# Go Back
+		*) status=1
+			main
+		;;
+		esac
+	done
 }
diff --git a/functions/thirdparty b/functions/thirdparty
--- a/functions/thirdparty
+++ b/functions/thirdparty
@@ -1,7 +1,11 @@
-#!/bin/bash
+#!/bin/bash#
+#
+# When adding (or removing) any functions remember to update the
+# source list and function below to reflect any changes you make
 
-dir="$(dirname "$0")"
+dir=$(dirname "$0")
 
+# Import apps functions; commented-out imports are omitted from the function below.
 source $dir/functions/apps/chrome
 source $dir/functions/apps/dropbox
 source $dir/functions/apps/oracle-java
@@ -13,9 +17,12 @@ source $dir/functions/apps/vlc
 
 # Install Third-Party Applications
 function thirdparty {
-	echo_message title "Starting 'thirdparty' function"
-	eval `resize`
-	THIRDPARTY=$(whiptail \
+	echo_message title "Starting 'thirdparty' function..."
+	# check exit status
+	EXITSTATUS=$?
+	if [ $EXITSTATUS = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "Third-Party Installation" \
 		--menu "\nWhat third-party software would you like to install?" \
@@ -31,13 +38,7 @@ function thirdparty {
 		'sublime_text'	'Sublime Text 3' \
 		'vlc'			'VLC Media Player' \
 		3>&1 1>&2 2>&3)
-
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		echo_message title "Starting '$THIRDPARTY' function..."
-		$THIRDPARTY
 	else
 		main
 	fi
 }
-
