more improvements

diff --git a/functions/installation b/functions/installation
--- a/functions/installation
+++ b/functions/installation
@@ -4,7 +4,7 @@
 function install_favs {
 	echo_message title "Starting 'install_favs' function..."
 	# Update the list of packages in 'data/favs-apps.list' to suit your preferences
-	install_from_list favs-apps "preferred apps" main
+	install_from_list favs-apps "preferred applications" main
 }
 
 # Install preferred development tools
@@ -47,8 +47,10 @@ function install_from_list() {
 				echo_message warning "Package '$PACKAGE' is not installed. Installing..."
 				# Admin privileges
 				elevate_privilege "dnf install -y $PACKAGE"
-				# Done
-				echo_message success 'Done.'
+				# Check if failed
+				if [[ $? != 0 ]]; then
+					echo_message error "Error installing '$PACKAGE'."
+				fi
 			else
 				# Show already installed message
 				echo_message info "Package '$PACKAGE' is installed."
diff --git a/functions/password b/functions/password
--- a/functions/password
+++ b/functions/password
@@ -6,33 +6,55 @@ function elevate_privilege() {
 	echo_message title "Starting 'elevate_privilege' function"
 	# check if current user is root
 	if [[ $EUID = 0 ]]; then
-		echo_message warning "You are logged in as the root user."
+		echo_message warning "You are logged in as the root user. Again, this is not recommended. :/"
 		# Running command without sudo
 		$@
 	else
 		# check sudo uptime to see if a password is needed
-		if [ $(sudo -n uptime 2>&1 | grep 'a password is required' | wc -l) = 1 ]; then
-			echo_message warning 'Requires admin privileges:'
-			PASSWORD=$(whiptail --passwordbox "\nRequires admin privileges to continue. \n\nPlease enter your password:\n" 12 48 --title "Password Required" 3>&1 1>&2 2>&3)
-			EXITSTATUS=$?
-			if [ $EXITSTATUS = 0 ]; then
-				$SUDOCMD -S <<< "$PASSWORD" $@
-				EXITSTATUS=$?
-				if [ $EXITSTATUS = 1 ]; then
-					echo_message error "Incorrect password. Aborting..."
-					# Draw window
-					whiptail --msgbox "Incorrect password. Sorry, try again." --title "Oops" 8 64
-					main
-				fi
+		if [ $(sudo -n uptime 2>&1 | grep 'a password is required' | wc -l) != 0 ]; then
+			echo_message warning 'Admin privileges required.'
+			# Draw window
+			PASSWORD=$(whiptail --title "Password Required" --passwordbox "\nRequires admin privileges to continue. \n\nPlease enter your password:\n" 12 48 3>&1 1>&2 2>&3)
+			if [ $? = 0 ]; then
+				# while loop for sudo attempts
+				COUNT=0
+				MAXCOUNT=3
+				while [ $COUNT -lt $MAXCOUNT ]; do
+					# pass the actual command
+					sudo -S <<< "$PASSWORD" echo
+					# if sudo command fails
+					if [ $? != 0 ];then
+						echo_message warning "Incorrect password."
+						# Prompt for password again
+						PASSWORD=$(whiptail --title "Password Error" --passwordbox "\nThe password you provided was not correct.\n\nPlease enter your password again:\n" 12 48 3>&1 1>&2 2>&3)
+						# Abort if user cancels
+						if [ $? = 1 ]; then
+							# Error message if user cancels
+							echo_message error "Password prompt cancelled. Aborting..."
+							main
+						fi
+						# Increase the count
+						let COUNT=COUNT+1
+						# Error message if too many attempts
+						if [[ "$COUNT" -eq "$MAXCOUNT" ]]; then
+							echo_message error "Too many failed password attempts. Aborting..."
+							whiptail --msgbox "Too many failed password attempts. Please try again." --title "Oops" 8 64
+							main
+						fi
+					else
+						# pass the actual command
+						sudo $@
+						break
+					fi
+				done
 			else
-				echo_message error "User cancelled password prompt. Aborting..."
-				# Draw window
-				whiptail --msgbox "Password is required to proceed. Sorry, try again." --title "Oops" 8 64
+				# Error message if user cancels
+				echo_message error "Password prompt cancelled. Aborting..."
+				whiptail --msgbox "Password is required to proceed. Please try again." --title "Oops" 8 64
 				main
 			fi
 		else
-			echo_message success "Admin privileges not required at this time."
-			$SUDOCMD $@
+			echo_message info "Admin privileges not required at this time."
 		fi
 	fi
 }
diff --git a/functions/update b/functions/update
--- a/functions/update
+++ b/functions/update
@@ -3,12 +3,16 @@
 # Perform system update
 function update {
 	echo_message title "Starting 'update' function"
+	echo_message header 'Performing system update...'
 	# Draw window
 	if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
-		# Update
-		echo_message info 'Performing system update...'
 		# Admin privileges
-		elevate_privilege "dnf update -y"
+		elevate_privilege "dnf upgrade -y"
+		# Check if failed
+		if [[ $? != 0 ]]; then
+			echo_message info "Nothing to update."
+			whiptail --title "Finished" --msgbox "Nothing to update." 8 64
+		fi
 		# Done
 		echo_message success 'System update complete.'
 		whiptail --title "Finished" --msgbox "System update complete." 8 64
