increase verbosity

diff --git a/functions/install_codecs b/functions/install_codecs
--- a/functions/install_codecs
+++ b/functions/install_codecs
@@ -2,14 +2,14 @@
 
 # Install OpenH264 Codecs
 function openh264_codec {
-	echo_message title "Starting 'openh264_codec' function"
+	echo_message header "Starting 'openh264_codec' function"
 	# Variables
 	NAME="OpenH264 Codec"
 	REPO="fedora-cisco-openh264"
 	PACKAGE=gstreamer1-plugin-openh264
 	# Check if package is installed
 	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
-		echo_message info "$NAME is not installed."
+		echo_message warning "Package '$PACKAGE' is not installed. Installing..."
 		# Add repository
 		echo_message info "Enabling '$REPO' repository..."
 		elevate_privilege "dnf config-manager --set-enabled $REPO"
@@ -18,19 +18,19 @@ function openh264_codec {
 		elevate_privilege "dnf install -y $PACKAGE"
 		# Done
 		echo_message success "Installation of '$PACKAGE' complete."
-		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
+		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
 		install_codecs
 	else
 		# Already installed
 		echo_message success "$NAME already installed."
-		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
+		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
 		install_codecs
 	fi
 }
 
 # Install FFmpeg Codecs
 function ffpmeg_codecs {
-	echo_message title "Starting 'ffpmeg_codecs' function"
+	echo_message header "Starting 'ffpmeg_codecs' function"
 	# Add RPM Fusion
 	if (eval `resize` && whiptail \
 		--title "Add RPM Fusion (free) Repository?" \
@@ -47,14 +47,14 @@ function ffpmeg_codecs {
 
 # Install GStreamer (free) Codecs
 function gstreamer_free {
-	echo_message title "Starting 'gstreamer_free' function"
+	echo_message header "Starting 'gstreamer_free' function"
 	# Update the list of packages in 'data/codecs-gstreamer-free.list' to suit your preferences
 	install_from_list codecs-gstreamer-free "GStreamer (free) multimedia codecs" install_codecs
 }
 
 # Install GStreamer (non-free) Codecs
 function gstreamer_nonfree {
-	echo_message title "Starting 'gstreamer_nonfree' function"
+	echo_message header "Starting 'gstreamer_nonfree' function"
 	# Add RPM Fusion 
 	if (eval `resize` && whiptail \
 		--title "Add RPM Fusion (non-free) Repository?" \
@@ -71,11 +71,9 @@ function gstreamer_nonfree {
 
 # Install Codecs
 function install_codecs {
-	echo_message title "Starting 'install_codecs' function"
-	# check exit status
-	if [ $? = 0 ]; then
-		# Draw window
-		$(eval `resize` && whiptail \
+	echo_message header "Starting 'install_codecs' function"
+	# Draw window
+	CODECS=$(eval `resize` && whiptail \
 		--notags \
 		--title "Multimedia Codecs" \
 		--menu "\nWhich multimedia codecs would you like to install?" \
@@ -87,7 +85,12 @@ function install_codecs {
 		'ffpmeg_codecs'		'FFmpeg Codecs' \
 		'openh264_codec'	'OpenH264 Codec' \
 		3>&1 1>&2 2>&3)
+	# check exit status
+	if [ $? = 0 ]; then
+		$CODECS
 	else
+		# Cancelled
+		echo_message info 'Multimedia codecs installation cancelled.'
 		main
 	fi
 }
diff --git a/functions/system_cleanup b/functions/system_cleanup
--- a/functions/system_cleanup
+++ b/functions/system_cleanup
@@ -5,7 +5,7 @@
 
 # Remove unused preinstalled apps
 function purge_unused {
-	echo_message title "Starting 'purge_unused' function..."
+	echo_message header "Starting 'purge_unused' function..."
 	# Check list
 	LIST=$(dirname "$0")'/data/purge.list'
 	# Draw window
@@ -14,7 +14,7 @@ function purge_unused {
 		--yesno "Current list of pre-installed apps to remove: \n\n$(cat $LIST) \n\nAre you sure you want proceed?" \
 		$LINES $COLUMNS $(( $LINES - 12 )) \
 		--scrolltext ) then
-		echo_message header 'Removing unused pre-installed apps...'
+		echo_message title 'Removing unused pre-installed apps...'
 		# Remove loop
 		for PACKAGE in $(cat $LIST); do
 			# Check if package is installed
@@ -33,44 +33,42 @@ function purge_unused {
 		# Done
 		echo_message success 'Removal of unused packages complete.'
 		whiptail --title "Finished" --msgbox "Unwanted pre-installed apps have been removed." 8 64
-		cleanup
+		system_cleanup
 	else
-		cleanup
+		system_cleanup
 	fi
 }
 
 # Remove Orphaned Packages
 function remove_orphans {
-	echo_message title "Starting 'remove_orphans' function"
-	echo_message header 'Removing orphaned packages...'
+	echo_message header "Starting 'remove_orphans' function"
+	echo_message title 'Removing orphaned packages...'
 	# Admin privileges
 	elevate_privilege "dnf autoremove -y"
 	# Done
 	echo_message success 'Orphaned packages have been successfully removed.'
-	whiptail --title "Finished" --msgbox "Orphaned packages have been successfully removed." 8 78
-	cleanup
+	whiptail --title "Finished" --msgbox "Orphaned packages have been successfully removed." 8 56
+	system_cleanup
 }
 
 # Clean Cache
 function clean_cache {
-	echo_message title "Starting 'clean_cache' function"
-	echo_message header 'Cleaning package cache...'
+	echo_message header "Starting 'clean_cache' function"
+	echo_message title 'Cleaning package cache...'
 	# Admin privileges
 	elevate_privilege "dnf clean packages"
 	# Done
 	echo_message success 'Package cache has been cleaned..'
-	whiptail --title "Finished" --msgbox "Package cache has been cleaned." 8 78
-	cleanup
+	whiptail --title "Finished" --msgbox "Package cache has been cleaned." 8 56
+	system_cleanup
 }
 
 # Cleanup System
-function cleanup {
-	echo_message title "Starting 'cleanup' function"
-	# check exit status
-	EXITSTATUS=$?
-	if [ $EXITSTATUS = 0 ]; then
-		# Draw window
-		$(eval `resize` && whiptail \
+function system_cleanup {
+	echo_message header "Starting 'system_cleanup' function"
+	echo_message title "Starting system cleanup..."
+	# Draw window
+	CLEANUP=$(eval `resize` && whiptail \
 		--notags \
 		--title "System Cleanup" \
 		--menu "\nWhat would you like to do?" \
@@ -79,8 +77,13 @@ function cleanup {
 		clean_cache			'Clean package cache' \
 		remove_orphans		'Remove orphaned packages' \
 		purge_unused		'Remove unused pre-installed packages' \
-		3>&1 1>&2 2>&3)
+		3>&1 1>&2 2>&3) then
+	# check exit status
+	if [ $? = 0 ]; then
+		$CLEANUP
 	else
+		# Cancelled
+		echo_message info 'System cleanup cancelled.'
 		main
 	fi
 }
diff --git a/functions/system_configure b/functions/system_configure
--- a/functions/system_configure
+++ b/functions/system_configure
@@ -3,7 +3,7 @@
 # Automatically set preferred gsettings keys as outlined in the 'gsettings.list' file
 # 'gsettings' can be obtained by executing "dconf watch /" and then manually changing settings
 function set_preferences {
-	echo_message title "Starting 'set_preferences' function..."
+	echo_message header "Starting 'set_preferences' function..."
 	echo_message info 'Setting preferred application-specific & desktop settings...'
 	# Variables
 	LIST=$(dirname "$0")'/data/gsettings.list'
@@ -13,13 +13,13 @@ function set_preferences {
 	done < "$LIST"
 	# Done
 	echo_message success 'Done.'
-	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
-	configure
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 56
+	system_configure
 }
 
 # Set preferred bash aliased by copying the 'aliases.list' file to ~/.bash_aliases
 function set_bash_aliases {
-	echo_message title "Starting 'set_bash_aliases' function..."
+	echo_message header "Starting 'set_bash_aliases' function..."
 	# Check list
 	ALIASES=$(dirname "$0")'/data/aliases.list'
 	# Draw window
@@ -33,34 +33,34 @@ function set_bash_aliases {
 		cp $ALIASES ~/.bash_aliases
 		echo_message success 'Bash aliases set successfully.'
 		whiptail --title "Finished" --msgbox "Bash aliases set successfully." 8 64
-		configure
+		system_configure
 	else
-		configure
+		system_configure
 	fi
 }
 
 # Put SELinux in permissive mode
 function selinux {
-	echo_message title "Starting 'selinux' function..."
+	echo_message header "Starting 'selinux' function..."
 	# Check if SELinux is aleady in permissive mode.
 	if [[ $(cat '/etc/selinux/config' | grep -q 'SELINUX=permissive'; echo $?) != 0 ]]; then
 		echo_message info 'Configuring SELinux to run in permissive mode...'
 		elevate_privilege "sed --in-place s/SELINUX=.*$/SELINUX=permissive/g /etc/selinux/config"
 		echo_message success 'Done.'
 		# Done
-		whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
-		configure
+		whiptail --title "Finished" --msgbox "Settings changed successfully." 8 56
+		system_configure
 	else
 		# Already configured
 		echo_message info "SELinux is aleady in permissive mode."
-		whiptail --title "Finished" --msgbox "SELinux is aleady in permissive mode." 8 78
-		configure
+		whiptail --title "Finished" --msgbox "SELinux is aleady in permissive mode." 8 56
+		system_configure
 	fi
 }
 
 # Add current user to sudo group (wheel)
 function add_to_sudo {
-	echo_message title "Starting 'add_to_sudo' function..."
+	echo_message header "Starting 'add_to_sudo' function..."
 	# Check if user is already in wheel
 	if [[ $(groups $USER | grep -q 'wheel'; echo $?) != 0 ]]; then
 		echo_message warning "This user account isn't in the wheel user group."
@@ -75,30 +75,30 @@ function add_to_sudo {
 			echo_message error "User cancelled action. Aborting..."
 			# Draw window
 			whiptail --msgbox "Current user not modified at this time." --title "Abort" 8 64
-			configure
+			system_configure
 		fi
 	else
 		# Already configured
 		echo_message info "User aleady in sudo group."
-		whiptail --title "Finished" --msgbox "Current user aleady has sudo privileges." 8 78
-		configure
+		whiptail --title "Finished" --msgbox "Current user aleady has sudo privileges." 8 56
+		system_configure
 	fi
 }
 
 # Enable Fedora Test Updates repository
 function test_updates {
-	echo_message title "Starting 'test_updates' function..."
+	echo_message header "Starting 'test_updates' function..."
 	echo_message info 'Enabling Fedora Test Updates repository...'
 	elevate_privilege "dnf --enablerepo=updates-testing check-update"
 	echo_message success 'Done.'
 	# Done
-	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
-	configure
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 56
+	system_configure
 }
 
 # limit number of concurrently installed packages 
 function limit_packages {
-	echo_message title "Starting 'limit_packages' function..."
+	echo_message header "Starting 'limit_packages' function..."
 	# maximum number of packages
 	MAX="5"
 	LIMIT=$(whiptail \
@@ -106,8 +106,8 @@ function limit_packages {
 		--title "Set Installed Package Limit" \
 		"\nLimit the number of packages that will be concurrently installed by DNF. The minimal number of packages is 2 and a value of 1 is unlimited. \n\nPlease enter a number between 1 and $MAX (default = 3):\n" \
 		14 72 3>&1 1>&2 2>&3)
-	EXITSTATUS=$?
-	if [ $EXITSTATUS = 0 ]; then
+	# check exit status
+	if [ $? = 0 ]; then
 		# check if input is a number
 		if ! [[ "$LIMIT" =~ '^[0-9]+$' ]] && ! [ "$LIMIT" -ge 1 -a "$LIMIT" -le $MAX ] ; then
 			echo_message error "Input was not a integer between 1 and $MAX. Aborting..."
@@ -121,22 +121,20 @@ function limit_packages {
 			elevate_privilege "sed --in-place s/installonly_limit=.*$/installonly_limit=${LIMIT}/g /etc/dnf/dnf.conf"
 			echo_message success 'Done.'
 			# Done
-			whiptail --title "Finished" --msgbox "Package limit changed successfully." 8 78
-			configure
+			whiptail --title "Finished" --msgbox "Package limit changed successfully." 8 56
+			system_configure
 		fi
 	else
-		configure
+		system_configure
 	fi
 }
 
 # Configure System
-function configure {
-	echo_message title "Starting 'configure' function..."
-	# check exit status
-	EXITSTATUS=$?
-	if [ $EXITSTATUS = 0 ]; then
-		# Draw window
-		$(eval `resize` && whiptail \
+function system_configure {
+	echo_message header "Starting 'system_configure' function..."
+	echo_message title "Starting system configuration..."
+	# Draw window
+	CONFIGURE=$(eval `resize` && whiptail \
 		--notags \
 		--title "Configure System" \
 		--menu "\nWhat would you like to do?" \
@@ -149,7 +147,12 @@ function configure {
 		add_to_sudo				'Add current user to sudoers group' \
 		test_updates			'Enable Fedora Test Updates repository' \
 		3>&1 1>&2 2>&3)
+	# check exit status
+	if [ $? = 0 ]; then
+		$CONFIGURE
 	else
+		# Cancelled
+		echo_message info 'System configuration cancelled.'
 		main
 	fi
 }
