fixed some string stuff

diff --git a/functions/apps/chrome b/functions/apps/chrome
--- a/functions/apps/chrome
+++ b/functions/apps/chrome
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Install Chrome
+# Download Chrome
 function download_chrome { 
 	# Variables
 	REPO="https://dl.google.com/linux/direct"
@@ -38,21 +38,22 @@ function download_chrome {
 	fi
 }
 
-# Google Chrome
+# Install Google Chrome
 function install_chrome {
 	NAME="Google Chrome"
 	# Install
 	echo_message title "Starting $NAME installation..."
 	VERSION=$(eval `resize` && whiptail \
-			--title "Google Chrome" \
-			--radiolist "Which version of Chrome would you like to install?" \
-			--ok-button "Install" \
-			--cancel-button "Go Back" \
-			$LINES $COLUMNS $(( $LINES - 12 )) \
-			"stable"	"Stable build" ON \
-			"beta"		"Beta build" OFF \
-			"unstable"	"Unstable build" OFF \
-			3>&1 1>&2 2>&3)
+		--title "$NAME" \
+		--radiolist "Which version of $NAME would you like to install?" \
+		--ok-button "Install" \
+		--cancel-button "Go Back" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		"stable"	"Stable build" ON \
+		"beta"		"Beta build" OFF \
+		"unstable"	"Unstable build" OFF \
+		3>&1 1>&2 2>&3)
+	# check exit status
 	if [ $? = 0 ]; then
 		case "${VERSION}" in
 			stable)
@@ -70,7 +71,7 @@ function install_chrome {
 		esac
 	else
 		# Cancelled
-		echo_message info 'Installation cancelled.'
+		echo_message info 'Installation of $NAME cancelled.'
 		install_thirdparty
 	fi
 }
diff --git a/functions/apps/rvm b/functions/apps/rvm
--- a/functions/apps/rvm
+++ b/functions/apps/rvm
@@ -1,50 +1,48 @@
 #!/bin/bash
 
-# Ruby Version Manager
+# Install RVM
 function install_rvm {
 	# Variables
 	NAME="Ruby Version Manager"
 	KEY="https://rvm.io/mpapis.asc "
-	# Draw window
-	eval `resize` 
-	EXITSTATUS=$?
-	if [ $EXITSTATUS = 0 ]; then
-		status="0"
-		while [ "$status" -eq 0 ]; do
-			VERSION=$(whiptail \
-			--title "$NAME" --radiolist \
-			"Which version of $NAME would you like to install?" \
-			--ok-button "Install" \
-			--cancel-button "Go Back" \
-			$LINES $COLUMNS $(( $LINES - 12 )) \
-			"stable"	"Stable version" ON \
-			"dev"		"Development version" OFF \
-			3>&1 1>&2 2>&3) 
-			# Change to lower case and remove spaces.
-			case "${VERSION}" in
-				stable)
-					# Import signing key
-					echo_message info "Importing $NAME signing key..."
-					command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
-					# Install
-					echo_message info 'Installing $NAME...'
-					\curl -sSL https://get.rvm.io | bash -s stable --ruby
-				;;
-				dev)
-					# Import signing key
-					echo_message info "Importing $NAME signing key..."
-					command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
-					# Install
-					echo_message info 'Installing $NAME...'
-					\curl -sSL https://get.rvm.io | bash
-				;;
-				*)
-					status=1 
-					install_thirdparty
-				;;
-			esac
-		done
+	# Install
+	echo_message title "Starting $NAME installation..."
+	VERSION=$(eval `resize` && whiptail \
+		--title "$NAME" \
+		--radiolist "Which version of $NAME would you like to install?" \
+		--ok-button "Install" \
+		--cancel-button "Go Back" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		"stable"	"Stable version" ON \
+		"dev"		"Development version" OFF \
+		3>&1 1>&2 2>&3)
+	# check exit status
+	if [ $? = 0 ]; then
+		case "${VERSION}" in
+			stable)
+				# Import signing key
+				echo_message info "Importing $NAME signing key..."
+				command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
+				# Install
+				echo_message info 'Installing $NAME...'
+				\curl -sSL https://get.rvm.io | bash -s stable --ruby
+			;;
+			dev)
+				# Import signing key
+				echo_message info "Importing $NAME signing key..."
+				command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
+				# Install
+				echo_message info 'Installing $NAME...'
+				\curl -sSL https://get.rvm.io | bash
+			;;
+			*)
+				status=1 
+				install_thirdparty
+			;;
+		esac
 	else
+		# Cancelled
+		echo_message info 'Installation cancelled.'
 		install_thirdparty
 	fi
 }
diff --git a/functions/apps/sublime-text b/functions/apps/sublime-text
--- a/functions/apps/sublime-text
+++ b/functions/apps/sublime-text
@@ -33,34 +33,36 @@ function download_sublime_text {
 	fi
 }
 
-# Sublime Text
+# Install Sublime Text
 function install_sublime_text {
-	EXITSTATUS="0"
-	while [ "$EXITSTATUS" -eq 0 ]; do
-		eval `resize`
-		VERSION=$(whiptail \
-		--title "Sublime Text" --radiolist \
-		"Which version of Sublime Text would you like to install?" \
+	NAME="Sublime Text"
+	# Install
+	echo_message title "Starting $NAME installation..."
+	VERSION=$(eval `resize` && whiptail \
+		--title "$NAME" \
+		--radiolist "Which version of $NAME would you like to install?" \
 		--ok-button "Install" \
 		--cancel-button "Go Back" \
 		$LINES $COLUMNS $(( $LINES - 12 )) \
 		"stable"	"Stable build" ON \
 		"dev"		"Beta build" OFF \
-		3>&1 1>&2 2>&3) 
-		# Change to lower case and remove spaces.
+		3>&1 1>&2 2>&3)
+	# check exit status
+	if [ $? = 0 ]; then
 		case "${VERSION}" in
 			stable)
 				download_sublime_text stable
-				EXITSTATUS=1
 			;;
 			dev)
 				download_sublime_text dev
-				EXITSTATUS=1
 			;;
 			*)
-				EXITSTATUS=1 
 				install_thirdparty
 			;;
 		esac
-	done
+	else
+		# Cancelled
+		echo_message info 'Installation of $NAME cancelled.'
+		install_thirdparty
+	fi
 }
diff --git a/functions/install_gnome b/functions/install_gnome
--- a/functions/install_gnome
+++ b/functions/install_gnome
@@ -15,20 +15,26 @@ function install_shell_extensions {
 
 # Install Codecs
 function install_gnome {
-	echo_message header "Starting 'install_gnome' function"
-	# check exit status
-	if ! (eval `resize` && whiptail \
+	echo_message header "Starting 'install_codecs' function"
+	NAME="GNOME Software"
+	echo_message title "Starting $NAME installation..."
+	# Draw window
+	GNOME=$(eval `resize` && whiptail \
 		--notags \
-		--title "Install GNOME Software" \
-		--menu "\nWhich GNOME Software would you like to install?" \
+		--title "Install $NAME" \
+		--menu "\nWhich $NAME would you like to install?" \
 		--ok-button "Install" \
 		--cancel-button "Go Back" \
 		$LINES $COLUMNS $(( $LINES - 12 )) \
 		'install_gnome_apps'		'GNOME Core Apps' \
 		'install_shell_extensions'	'GNOME Shell Extensions' \
-		3>&1 1>&2 2>&3) then
+		3>&1 1>&2 2>&3)
+	# check exit status
+	if [ $? = 0 ]; then
+		$GNOME
+	else
 		# Cancelled
-		echo_message info 'Installation cancelled.'
+		echo_message info "$NAME installation cancelled."
 		main
 	fi
 }
